name: fordev
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter    

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.4
  equatable: ^2.0.5
  get: ^4.6.5
  flutter_secure_storage: ^6.0.0
  carousel_slider: ^4.1.1
  intl: ^0.17.0
  localstorage: ^4.0.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.1
  test: ^1.21.4
  faker: ^2.0.0
  build_runner: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/
#flutter pub run build_runner build --delete-conflicting-outputs